server:
  port: 8016
  #注册中心-此时注册中去用于找到config-server
eureka:
  client:
    #设置服务注册中心的URL
    service-url:
      defaultZone: http://localhost:8081/eureka/

#应用名称，配置文件名，此时:congif-client-dev.yml
spring:
  application:
    name: config-client
  cloud:
    config:
      discovery:
        enabled: true
        # config server 的服务id
        service-id: config-server
      # 环境
      # profile: dev
