spring:
  application:
    name: service
#  devtools:
#    restart:
#      enabled: true #设置开启热部署
#  thymeleaf:
#    cache: false
eureka:
  instance:
    hostname: service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/
server:
  port: 8083
ribbon:
  eureka:
    enabled: true