spring:
  application:
    name: eureka
server:
  port: 8081
eureka:
  instance:
    hostname: eureka-8081
    prefer-ip-address: true
   # instance-id: 127.0.0.1
    #发送心跳给server的频率，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1
    #Serv er从收到client后，下一次收到心跳的间隔时间。超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1
  server:
    #关闭自我保护
    enable-self-preservation: false
    #清理服务间隔时间，毫秒
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://127.0.0.1:8081/eureka/
    healthcheck:
      #开启健康检查，需要引入actuator
      enabled: true